# Generated by Django 3.1 on 2020-08-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIdentification',
            fields=[
                ('img_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to=None)),
            ],
        ),
    ]
