# Generated by Django 3.1 on 2020-09-01 09:18

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageIdentification',
            fields=[
                ('img_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('identification_text', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
        migrations.CreateModel(
            name='MAppingModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('value', 'value'), ('label', 'label')], default='label', max_length=20)),
                ('x_axis', models.IntegerField()),
                ('y_axis', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('block', models.CharField(max_length=50)),
                ('csv_column', django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=510, size=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyinvoice.imagemodel')),
            ],
            options={
                'ordering': ['created_date'],
            },
        ),
    ]
