# Generated by Django 3.1.1 on 2020-09-04 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplyinvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=None)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplyinvoice.imagemodel')),
            ],
        ),
    ]
