# Generated by Django 3.1.1 on 2020-09-04 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplyinvoice', '0002_pdfmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfmodels',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdfmodels',
            name='model_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='supplyinvoice.imagemodel'),
        ),
    ]
