# Generated by Django 3.1.1 on 2020-09-04 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyinvoice', '0003_auto_20200904_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfmodels',
            name='model_id',
        ),
    ]
