# Generated by Django 3.1.1 on 2020-09-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyinvoice', '0005_auto_20200908_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='file',
            name='pdf_files',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
