# Generated by Django 3.1.1 on 2020-09-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplyinvoice', '0006_auto_20200908_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageIdentification',
        ),
    ]
