# Generated by Django 3.1.1 on 2020-09-08 06:19

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyinvoice', '0007_delete_imageidentification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappingmodels',
            name='block',
        ),
        migrations.RemoveField(
            model_name='mappingmodels',
            name='csv_column',
        ),
        migrations.RemoveField(
            model_name='mappingmodels',
            name='height',
        ),
        migrations.RemoveField(
            model_name='mappingmodels',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mappingmodels',
            name='text',
        ),
        migrations.RemoveField(
            model_name='mappingmodels',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mappingmodels',
            name='width',
        ),
        migrations.RemoveField(
            model_name='mappingmodels',
            name='x_axis',
        ),
        migrations.RemoveField(
            model_name='mappingmodels',
            name='y_axis',
        ),
        migrations.AddField(
            model_name='mappingmodels',
            name='mapping',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
