# Generated by Django 3.1.1 on 2020-09-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyinvoice', '0008_auto_20200908_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingmodels',
            name='mapping',
            field=models.JSONField(),
        ),
    ]
