# Generated by Django 3.1.1 on 2020-09-08 06:34

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('supplyinvoice', '0009_auto_20200908_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingmodels',
            name='mapping',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
